const express = require('express')
const router = express.Router()
const controller = require('../controllers/chat.controller')
const upload = require('../middleware/multer')

router.post('/new/channel', controller.createNewChannel)
router.get('/list/active', controller.listActive)
router.get('/list/recent', controller.listRecent)
router.post('/list/noperator', controller.listChatNoOperatorByWebsite)
router.post('/list/active/bywebsite', controller.listActiveChatByWebsite)
router.post('/list/recent/bywebsite', controller.listRecentChatByWebsite)
router.post('/findbyid', controller.getChatById)
router.post('/new/message/operator', controller.sendNewMessageAsOperator)
router.post('/new/message/guest', controller.sendNewMessageAsGuest)
router.post('/assign/operator', controller.assignOperator)
router.post('/attach/guest', upload.single('attach'), controller.sendImageAsGuest)
router.post('/attach/operator', upload.single('attach'), controller.sendImageAsOperator)
router.post('/close', controller.endChatById)
router.post('/transfer', controller.transferChatById)

module.exports = router